### ISSUE TITLE
Dydx suggestions

### ISSUE THREAD

**Issue by ith-harvey** [makerdao/pyexchange#125]
So since Dydx utilizes a `market_id` it would be nice if that var name was used throughout the file instead of utilizing different variables names to store the `market_id`.
https://github.com/makerdao/pyexchange/blob/54937010611e48bbcec64e95614518173e0cb66d/pyexchange/dydx.py#L164

Here is another example where I would use that `market_id` var name:
https://github.com/makerdao/pyexchange/blob/54937010611e48bbcec64e95614518173e0cb66d/pyexchange/dydx.py#L192

**Comment by MikeHathaway** [comment]
Addressed with this PR: https://github.com/makerdao/pyexchange/pull/126
